include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    type_annotate_public_apis: true

analyzer:
  errors:
    always_declare_return_types: warning
    type_annotate_public_apis: warning
