name: arara
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '^3.1.3'

dependencies:
  cupertino_icons: ^1.0.2
  diacritic: ^0.1.4
  flutter:
    sdk: flutter
  flutter_image_slideshow: ^0.1.6
  flutter_riverpod: ^2.4.0
  form_builder_validators: ^9.1.0
  get_it: ^7.6.4
  get_storage: ^2.1.1
  go_router: ^11.1.2
  json_annotation: ^4.8.1
  material_design_icons_flutter: ^7.0.7296
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
