name: arara
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '^3.1.3'

dependencies:
  cupertino_icons: ^1.0.2
  diacritic: ^0.1.4
  flutter:
    sdk: flutter
  flutter_image_slideshow: ^0.1.6
  flutter_riverpod: ^2.4.9
  form_builder_validators: ^9.1.0
  get_storage: ^2.1.1
  go_router: ^12.1.3
  intl: ^0.18.1
  json_annotation: ^4.8.1
  material_design_icons_flutter: ^7.0.7296
  share_plus: ^7.2.1
  shimmer: ^3.0.0
  url_launcher: ^6.2.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
